"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
import pymysql
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)q4b1hz%yar1gs^u%c1&oqi^bgqwz-7ey1*4*+^=m71yt5(f!*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'filmes',
    'rest_framework',
    'sorl.thumbnail',
    'galleryfield',
    # 'crispy_forms',
    # 'eventtools',
    'ckeditor',
    'ckeditor_uploader',
    "corsheaders",
    'drf_yasg',
    'nested_admin',
    'easy_thumbnails',
    'filer',
]
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    # ]
}
# CORS_ALLOWED_ORIGINS = [
#     # "https://example.com",
#     # "https://sub.example.com",
#     "http://localhost:8000",
#     "http://127.0.0.1:8000",
# ]
# CSRF_TRUSTED_ORIGINS = [
#     "http://localhost:8000",
# ]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
pymysql.install_as_MySQLdb()
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        # 'ENGINE': 'mysql.connector.django',
        'NAME': 'primaidade',
        'USER': 'root',
        'PASSWORD': '',
        'PORT': '3306',
        'HOST':'localhost',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static/"),


]

MEDIA_URL = "/media/images/"
MEDIA_ROOT = os.path.join(BASE_DIR, '/media/images/')

STATIC_ROOT = '/static/'
# MEDIA_URL = "/media/images/"
# MEDIA_ROOT = '/home/valeutea/backend.valentinapelayoatilano.com/media/images/'

# STATIC_ROOT = '/home/valeutea/backend.valentinapelayoatilano.com/static'



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SENDFILE_ROOT = os.path.join(BASE_DIR, 'media/images/')
SENDFILE_URL = "media/"

DJANGO_GALLERY_FIELD_CONFIG = {
    # "bootstrap_version": 4,
    # "assets": {
    #     "jquery": "path/or/url/to/jquery.js",
    #     "bootstrap_css": "path/or/url/to/bootstrap.css",
    #     "bootstrap_js": "path/or/url/to/bootstrap.js",
    #     "extra_js": [],
    #     "extra_css": [],
    # },

    "thumbnails": {
        "size": "120x120",
        "quality": 80
    },

    "jquery_file_upload_ui_options": {
        "autoUpload": True,
        "imageMaxWidth": 1024,
        "imageMaxHeight": 1024,
    },

    "jquery_file_upload_ui_sortable_options": {
        "disabled": False,
        "delay": 300,
        "animation": 200,
    },
    "prompt_alert_if_changed_on_window_reload": True,
    "widget_hidden_input_css_class": "django-galleryfield",

}
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"