# Generated by Django 5.0.2 on 2024-02-18 18:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comercial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pais', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('estreia', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('tv', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('vod', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('realizacao', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('argumentacao', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('producao', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Festivais',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('festival', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('genre', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('suport', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('duration', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('budget', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Financiamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orcamento', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('financiadores', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imprensa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('link', models.TextField(blank=True, max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='OutrosVideos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('link', models.TextField(blank=True, max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='PalavrasSobre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('texto', models.TextField(blank=True, max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Premios',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('premio', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnicos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tecnico', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('accao', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('realizador', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(default='', max_length=250, unique_for_date='id')),
                ('sinopse', models.TextField(blank=True, max_length=2500)),
                ('trailer', models.URLField(blank=True, default='')),
                ('com', models.TextField(blank=True, max_length=2500)),
                ('vozes', models.TextField(blank=True, max_length=2500)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('video', models.URLField(blank=True, default='')),
                ('distribuiçao', models.ManyToManyField(blank=True, to='filmes.comercial')),
                ('equipa', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='filmes.equipa')),
                ('festivais', models.ManyToManyField(blank=True, to='filmes.festivais')),
                ('ficha_tecnica', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='filmes.fichatecnica')),
                ('financiamento', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='filmes.financiamento')),
                ('imprensa', models.ManyToManyField(blank=True, to='filmes.imprensa')),
                ('outros_videos', models.ManyToManyField(blank=True, to='filmes.outrosvideos')),
                ('palavras', models.ManyToManyField(blank=True, to='filmes.palavrassobre')),
                ('premios', models.ManyToManyField(blank=True, to='filmes.premios')),
                ('tecnicos', models.ManyToManyField(blank=True, to='filmes.tecnicos')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('filme', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='filmes.filme')),
            ],
        ),
    ]
