# Generated by Django 3.2.18 on 2024-03-07 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import galleryfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('A', 'Production'), ('B', 'Co-Production'), ('C', 'Future')], default='', max_length=1)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('realizador', models.CharField(blank=True, max_length=255, null=True)),
                ('sinopse', models.TextField(blank=True, max_length=2500, null=True)),
                ('trailer', models.URLField(blank=True, default='', null=True)),
                ('ano', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('genero', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('suporte', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('duraçao', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('budget', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('com', models.TextField(blank=True, max_length=2500, null=True)),
                ('vozes', models.TextField(blank=True, max_length=2500, null=True)),
                ('equipa_argumento', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('equipa_producao', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('equipa_realizacao', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ficha_tecnica_ano', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ficha_tecnica_duracao', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ficha_tecnica_genero', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ficha_tecnica_suporte', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('financiamento_financiadores', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('financiamento_orcamento', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('galery', galleryfield.fields.GalleryField(blank=True, null=True, target_model='galleryfield.BuiltInGalleryImage', verbose_name='Photos')),
                ('videodrop', models.URLField(blank=True, default='', null=True)),
                ('video_page', models.URLField(blank=True, default='', null=True)),
                ('slug', models.SlugField(default='', max_length=250, unique_for_date='id')),
                ('thumbnail', filer.fields.image.FilerImageField(blank=True, help_text='thumbnail', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('accao', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('filme', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='filmes.filme')),
            ],
        ),
        migrations.CreateModel(
            name='Premios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premio', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('filme', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='filmes.filme')),
            ],
        ),
        migrations.CreateModel(
            name='PalavrasSobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('texto', models.TextField(blank=True, max_length=2500)),
                ('filme', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='filmes.filme')),
            ],
        ),
        migrations.CreateModel(
            name='OutrosVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('link', models.TextField(blank=True, max_length=2500)),
                ('filme', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='filmes.filme')),
            ],
        ),
        migrations.CreateModel(
            name='Imprensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artigo', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('titulo', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('nome', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('link', models.TextField(blank=True, max_length=2500)),
                ('filme', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='filmes.filme')),
            ],
        ),
        migrations.CreateModel(
            name='Festivais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festival', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('filme', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='filmes.filme')),
            ],
        ),
        migrations.CreateModel(
            name='Comercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('estreia', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('tv', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('vod', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('filme', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='filmes.filme')),
            ],
        ),
    ]
