# Generated by Django 5.0.2 on 2024-02-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imprensa',
            name='pais',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='outros_videos',
            field=models.ManyToManyField(blank=True, related_name='outros_videos', to='filmes.outrosvideos'),
        ),
    ]
