# Generated by Django 5.0.2 on 2024-02-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsPage',
            new_name='FilmesPage',
        ),
    ]
