# Generated by Django 5.0.2 on 2024-02-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_imprensa_pais_alter_filme_outros_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='category',
            field=models.CharField(choices=[('A', 'Production'), ('B', 'Co-Production'), ('C', 'Future')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='filme',
            name='distribuiçao',
            field=models.ManyToManyField(blank=True, related_name='distribuiçao', to='filmes.comercial'),
        ),
        migrations.RemoveField(
            model_name='filme',
            name='equipa',
        ),
        migrations.AlterField(
            model_name='filme',
            name='festivais',
            field=models.ManyToManyField(blank=True, related_name='festivais', to='filmes.festivais'),
        ),
        migrations.RemoveField(
            model_name='filme',
            name='ficha_tecnica',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='financiamento',
        ),
        migrations.AlterField(
            model_name='filme',
            name='imprensa',
            field=models.ManyToManyField(blank=True, related_name='imprensa', to='filmes.imprensa'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='palavras',
            field=models.ManyToManyField(blank=True, related_name='palavras', to='filmes.palavrassobre'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='premios',
            field=models.ManyToManyField(blank=True, related_name='premios', to='filmes.premios'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='tecnicos',
            field=models.ManyToManyField(blank=True, related_name='tecnicos', to='filmes.tecnicos'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='filme',
            name='equipa',
            field=models.ManyToManyField(blank=True, related_name='equipa', to='filmes.equipa'),
        ),
        migrations.AddField(
            model_name='filme',
            name='ficha_tecnica',
            field=models.ManyToManyField(blank=True, related_name='ficha_tecnica', to='filmes.fichatecnica'),
        ),
        migrations.AddField(
            model_name='filme',
            name='financiamento',
            field=models.ManyToManyField(blank=True, related_name='financiamento', to='filmes.financiamento'),
        ),
    ]
