# Generated by Django 5.0.2 on 2024-02-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_rename_filmespage_filmepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='filmepage',
            name='category',
            field=models.CharField(default='all', max_length=250),
        ),
    ]
