# Generated by Django 5.0.2 on 2024-02-20 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0004_remove_filme_outros_videos_outrosvideos_filme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='distribuiçao',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='equipa',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='festivais',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='ficha_tecnica',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='financiamento',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='imprensa',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='palavras',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='premios',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='tecnicos',
        ),
        migrations.AddField(
            model_name='comercial',
            name='filme',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='filmes.filme'),
        ),
        migrations.AddField(
            model_name='equipa',
            name='filme',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='filmes.filme'),
        ),
        migrations.AddField(
            model_name='festivais',
            name='filme',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='filmes.filme'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='filme',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='filmes.filme'),
        ),
        migrations.AddField(
            model_name='financiamento',
            name='filme',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='filmes.filme'),
        ),
        migrations.AddField(
            model_name='imprensa',
            name='filme',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='filmes.filme'),
        ),
        migrations.AddField(
            model_name='palavrassobre',
            name='filme',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='filmes.filme'),
        ),
        migrations.AddField(
            model_name='premios',
            name='filme',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='filmes.filme'),
        ),
        migrations.AddField(
            model_name='tecnicos',
            name='filme',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='filmes.filme'),
        ),
    ]
