# Generated by Django 5.0.2 on 2024-02-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0005_remove_filme_distribuiçao_remove_filme_equipa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='ano',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='budget',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='duraçao',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='genero',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='suporte',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='FichaTecnica',
        ),
    ]
