# Generated by Django 5.0.2 on 2024-02-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0006_filme_ano_filme_budget_filme_duraçao_filme_genero_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='video',
            new_name='video_page',
        ),
        migrations.AddField(
            model_name='filme',
            name='thumbnail',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='videodrop',
            field=models.URLField(blank=True, default=''),
        ),
    ]
