# Generated by Django 5.0.2 on 2024-02-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0007_rename_video_filme_video_page_filme_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='video_page',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
