# Generated by Django 5.0.2 on 2024-02-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0008_alter_filme_video_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='sinopse',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='trailer',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='video_page',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
