# Generated by Django 5.0.2 on 2024-02-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0009_alter_filme_sinopse_alter_filme_trailer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='com',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='vozes',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
