# Generated by Django 5.0.2 on 2024-02-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0010_alter_filme_com_alter_filme_vozes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='videodrop',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
