# Generated by Django 5.0.2 on 2024-02-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0011_alter_filme_videodrop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
