# Generated by Django 5.0.2 on 2024-02-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0013_remove_financiamento_filme_filme_equipa_argumento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imprensa',
            old_name='pais',
            new_name='artigo',
        ),
        migrations.AddField(
            model_name='imprensa',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
