# Generated by Django 5.0.2 on 2024-03-06 16:58

import galleryfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0014_rename_pais_imprensa_artigo_imprensa_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='galery',
            field=galleryfield.fields.GalleryField(blank=True, null=True, target_model='galleryfield.BuiltInGalleryImage', verbose_name='Photos'),
        ),
    ]
