# Generated by Django 5.0.2 on 2024-03-06 17:14

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0015_filme_galery'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='logo',
            field=filer.fields.image.FilerImageField(blank=True, help_text='thumbnail', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
